Repository openSUSE/software-o-o, pull requests merged in 2019-05, with the labels that each got.

#556 Fix package show when there is not description
  app/helpers/package_helper.rb
Labels: Bug :skull:, priority :fast_forward:

#554 Add rake tasks for Rubocop & use auto-gen-only-exclude for the todo file
  .rubocop_todo.yml
  .travis.yml
  lib/tasks/rubocop.rake
Labels: linters :gem:

#559 Use a single Leap action to render all releases
  app/controllers/distributions_controller.rb
  app/helpers/distribution_helper.rb
  config/routes.rb
  test/integration/distributions_test.rb
Labels: Feature, Refactoring :wrench:

#562 Fix conditional to show testing state
  app/views/distributions/_distribution.html.erb
Labels: Bug :skull:, UI :eyes:

#577 Fix issue with not applied/saved search settings
  app/assets/javascripts/search-settings.js
Labels: Bug :skull:

#584 Pass leap version to documentation partial
  app/views/distributions/_distribution.html.erb
Labels: Bug :skull:, UI :eyes:, priority :fast_forward:
